apiVersion: v1
kind: Service
metadata:
  name: __CI_PROJECT_NAME__
  namespace: __NAMESPACE__
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: __CI_PROJECT_NAME__
